language: scala
scala:
- 2.12.4
- 2.11.12
sudo: false
script: $TRAVIS_BUILD_DIR/travis/build.sh
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/.sbt
env:
  global:
  - secure: s7s+coS/4WB8emXCxvroqoWq7QNwmxjl1/3oJloxaW2ydDdKdFDP6/PNzUr647iK6rUMKPyyl5iWchRxemPkvNE7Dkq7HjCgxU8ZN4E3nvAER8tb+iMzw98EUbvjClZ1hcjCeoY6zOH/tr3WWQkNxubhXN8dx4uHgDRWAoawpIn3/+927lnefLHqrvcDleOll6jvJbTRyIJ/v44HNh87QuL7zXYVjdAeO3iXFwHQsU7upkMs1Lo51EaiaaXEFvQx3LqwSjYbUz27WBHw0iVx0B7RPwAUuS0kfnC7xbBExRfEuKq8pfvbsaRpgk8eLkT1e6NEfkPeEbg38HZek6ergcROcx/Lmn9vOGGydtrGkBKRzWGxAfKMurWyGX7iHBGK/GLGY4zxfqgXDHLwpvHdAQhTFmZQc80U4y7bbg28Vs0HmNTfuNwM+JTGDAvB3EBt24bICbFbMfhSXgLIMPLu2guIcw5SjIjNUg9O0hosm14NJYzwDNY9gFpafj5iGf0FvPNeOCthcHzdsE/dkAvMtp0LwJRl60zZDXv89m0ZvG1J0RYPI305xe5+8oaoNxxwnKlqGVWcviCglO8DbAGy4lLOLrbZovcUSdtq8jCNtUsA7ymkrX/NP8vb2FistYZ7JhANiZpy91VAIT6qXRTt3VzHzwFvS49chML4gR3sUt4=
  - secure: nolBhN2PWdrXLho2e4crFUQd1J5c1DGvgfMliNbS7BJMOzs3iOOlaVb0yQLHFDUJTfBz6Ri017IB+UuEWMmgOVCArri7wXWdfaLucPsp7WUYVKq8YCbCq3mj65virHEkmhyA6BCfAe5o672yy2Wi1sPAWoJg6qm5wY+yZDICzhIYcunGdZh1J765SsfBMflWU5Et4NNP4rx6iWLMxImd0cSHdUPlDGXrV+aONx0bVEGDjRv9JETEoMv4AoVPc14E0cTX28yt1kPJLBOj8mnDHlWLKlmQsLuaxNFsnKsm5F5jl69cn860afqtP8xsU6o5yYyV+06qMMjoHREfmEW0iFsDLUAi+5em4ae1kcmUzJFp06Gm5npUmvNRtrZ0HniFB8bFlZWJvHhfWZntG1rxy4F5wCFFJviFXlZSmAN6fPzerzLaNfD03ftclZHNjocF2NUVGBBPfKNvyfoEtJ4D8mm27m5IOCPaPs2NmLEgR0nWCA/KQZoWqRjUvqGdl+I/jf9FF+T2dlrqUGrRtS5uR54XAc3hWen+F8T6uPCU2WXW0Mvc5cOv64/ePz9vqggpYAwTKXzvtWGva/fwXDrpnCsW8FLxLRhYhR0qzSf/mu5X+D9x3o5T3zptuhHW3X4/iU6CkfH2FqJdSdQ5qyXnKl447JQ06fPMqtQrJf2d5Ew=
  - secure: QkgJujcFRlUOF9gd6mKMZV1Z4A4ociMOwYxo42Vd0gKa4XHXzxx7EyQYRWBl38EYFdu1Ehhsg00neJNe3kPiz+fISlezQmh7EX63RFW2DixySHOW3YTqV97wwXRt30DM7lEjn2Ao8xR0K3r/s2NWdYiG5j2KKVNUZs1UjqANEVuAVmi7AWosMyPY91LNrV98GRMcFtZ6Ej0Z/rjgwxj5SiicrmqjgUvhQDaR5HMtKJPWMBt54P+5Kqv++NCy4nPY32Gq3Mez9OmKI3wMYRkurnptXejzkrutAck4TZvtroxnKNExAWkcdex0deUkw6WHF5Ju6XTWwbps1ULJ3GlEw8fuMkEcUZ/vWOLlNrD9FswJtm53m0sQa9t2R6hrc2zylYosC/AVyfvmqSkboYIMcEoIyJF85wHCmJVmXRlhjiVxOdt3meVG/8fcC/tv9xVZ6vh8T8ElToylUB1baoG3LEpxIeTyIQ/ymXLtB9GvG/CBcTcIf3/ImysbQhz2TkCdrQalSfNQnjECCJIOuBPkHEAukIKd+8SHwmwGelvOwOnB/ksYadXiGbAPf3zGPW4UPbAdcomySl/d5/l4MYPh/jgRZzoEcGk7VHGt/ABmhaDZnL8tt81MiHS+votPamrbKsYcWYZaD0Q2CxgWH/AGnH0BN/yv2zIWihn/POlbTB0=
  - secure: l3Oq0Pvh4lFP3msuf1MapbYxg7PkJmugcehOi6EO4BALHaPimFlQV9AGNk8W6i7nyELP3YPEcZlbd9/lw9d9lAjS0mJIr2OFP0ZGbHOZ2BiQciYObzYF0ZoRGrvsiZyRqj1QO8ogyeegOr5yYZ6u229shogl/XmX4P7rMvoyNZuUVf70E4NjSMCP/lKo6s1ERaDoMYpC/uYD0teDu3NjgZiABqKR+A/lP+QDETpjLXg2XaYycdwm0aMW7M2aBt8evn2oDus2JFp4YsMlVcdi424fDv3wF/L14wHSYUSGNyXCM23hT+c8ayiqpa5qo1SjRY+a9nfP2OKh39w8WewDAsTfP3Xf/9DnsuZOnViAn/T4gu3xvLigpCXXTcBX0kpImNSKqnpMZD+8WjxWvWmKUbilRUDmEMUOlqc0/yVlJQmB3D2zWsaIrzOR9j8zOkl3DpGN6mVz9lsxvVCtp2de03qzTYfQ4SVv6iPUPJdEKusevK1Ea+2aiBRI9TLG/+Otwhwa9pHxXaj4boUEDGK5u22/WJbSqzZCDwifzmXn38YxPU9EtH9rfve5uOINQJjMVcedhg7dMCjXfkIF/CnSdTZ+/LbJ8ClJ6qpRaUiOXIvJ4v/aBycpw/28DHv4m+URErAbefdsEsiQTXDo0mEb3IQFU2WDH0YydoJSvpnsmn4=

before_install:
  - docker run -d --net host --name zookeeper wurstmeister/zookeeper
  - docker run -d --net host --name kafka --env KAFKA_ADVERTISED_HOST_NAME=localhost --env KAFKA_ZOOKEEPER_CONNECT=localhost:2181 wurstmeister/kafka

after_failure:
  - docker exec -it kafka /opt/kafka_2.12-1.0.0/bin/kafka-consumer-groups.sh --new-consumer --bootstrap-server localhost:9092 --group sub1 --describe
  - docker exec -it kafka /opt/kafka_2.12-1.0.0/bin/kafka-consumer-groups.sh --new-consumer --bootstrap-server localhost:9092 --group sub2 --describe
  - docker logs kafka

addons:
  hosts:
    - kafka-test
